### Sign Up Request
POST {{$dotenv API_URL}}/auth/sign-up
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "example-password"
}

### Login Request
POST {{$dotenv API_URL}}/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "example-password"
}
